import React, { useState } from "react";
import { base44 } from "@/api/base44Client";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Plus, Receipt, DollarSign, Calendar, Download, Eye, Loader2 } from "lucide-react";
import { Label } from "@/components/ui/label";

const STATUS_CONFIG = {
  sent: { label: "Sent", className: "bg-blue-50 text-blue-700 border-blue-200" },
  paid: { label: "Paid", className: "bg-emerald-50 text-emerald-700 border-emerald-200" },
  overdue: { label: "Overdue", className: "bg-red-50 text-red-700 border-red-200" },
};

export default function InvoicesTab({ invoices, projectId, projectName, clientEmail, isClient, onInvoiceCreated }) {
  const [open, setOpen] = useState(false);
  const [viewInvoice, setViewInvoice] = useState(null);
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ amount: "", description: "", due_date: "" });

  const handleCreate = async () => {
    if (!form.amount || !form.description || !form.due_date) return;
    setCreating(true);

    const invoiceNumber = `INV-${Date.now().toString(36).toUpperCase()}`;

    await base44.entities.Invoice.create({
      project_id: projectId,
      amount: parseFloat(form.amount),
      description: form.description,
      due_date: form.due_date,
      status: "sent",
      invoice_number: invoiceNumber,
    });

    await base44.entities.Activity.create({
      project_id: projectId,
      type: "invoice_created",
      description: `Invoice ${invoiceNumber} created for $${form.amount}`,
      actor_name: "Filmmaker",
    });

    setForm({ amount: "", description: "", due_date: "" });
    setCreating(false);
    setOpen(false);
    onInvoiceCreated();
  };

  const handleStatusChange = async (invoiceId, newStatus) => {
    await base44.entities.Invoice.update(invoiceId, { status: newStatus });
    onInvoiceCreated();
  };

  const handlePrint = (invoice) => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
      <head>
        <title>Invoice ${invoice.invoice_number}</title>
        <style>
          body { font-family: 'Inter', Arial, sans-serif; padding: 40px; color: #1a1a1a; }
          .header { display: flex; justify-content: space-between; margin-bottom: 40px; border-bottom: 2px solid #f4f4f5; padding-bottom: 24px; }
          .logo { font-size: 24px; font-weight: 700; }
          .invoice-number { color: #71717a; }
          .details { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-bottom: 40px; }
          .label { font-size: 12px; color: #a1a1aa; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
          .value { font-size: 15px; font-weight: 500; }
          .amount-section { background: #fafafa; padding: 24px; border-radius: 12px; margin-bottom: 24px; }
          .amount { font-size: 32px; font-weight: 700; }
          .description { margin-top: 16px; color: #52525b; line-height: 1.6; }
          .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #f4f4f5; color: #a1a1aa; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="logo">FilmOS</div>
            <div class="invoice-number">${invoice.invoice_number}</div>
          </div>
          <div style="text-align:right">
            <div class="label">Status</div>
            <div class="value">${(invoice.status || 'sent').toUpperCase()}</div>
          </div>
        </div>
        <div class="details">
          <div>
            <div class="label">Project</div>
            <div class="value">${projectName}</div>
          </div>
          <div>
            <div class="label">Client</div>
            <div class="value">${clientEmail}</div>
          </div>
          <div>
            <div class="label">Invoice Date</div>
            <div class="value">${format(new Date(invoice.created_date), "MMMM d, yyyy")}</div>
          </div>
          <div>
            <div class="label">Due Date</div>
            <div class="value">${format(new Date(invoice.due_date), "MMMM d, yyyy")}</div>
          </div>
        </div>
        <div class="amount-section">
          <div class="label">Amount Due</div>
          <div class="amount">$${invoice.amount?.toFixed(2)}</div>
          <div class="description">${invoice.description}</div>
        </div>
        <div class="footer">Generated by FilmOS</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="space-y-6">
      {/* Create invoice */}
      {!isClient && (
        <div className="flex justify-end">
          <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger asChild>
              <Button className="bg-zinc-900 hover:bg-zinc-800">
                <Plus className="w-4 h-4 mr-2" />
                Create Invoice
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create Invoice</DialogTitle>
              </DialogHeader>
              <div className="space-y-4 mt-4">
                <div>
                  <Label>Amount ($)</Label>
                  <Input
                    type="number"
                    min="0"
                    step="0.01"
                    placeholder="0.00"
                    value={form.amount}
                    onChange={(e) => setForm({ ...form, amount: e.target.value })}
                  />
                </div>
                <div>
                  <Label>Description</Label>
                  <Textarea
                    placeholder="Describe the work or deliverables..."
                    value={form.description}
                    onChange={(e) => setForm({ ...form, description: e.target.value })}
                    rows={3}
                  />
                </div>
                <div>
                  <Label>Due Date</Label>
                  <Input
                    type="date"
                    value={form.due_date}
                    onChange={(e) => setForm({ ...form, due_date: e.target.value })}
                  />
                </div>
                <Button
                  onClick={handleCreate}
                  disabled={creating || !form.amount || !form.description || !form.due_date}
                  className="w-full bg-zinc-900 hover:bg-zinc-800"
                >
                  {creating ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Receipt className="w-4 h-4 mr-2" />}
                  Create Invoice
                </Button>
              </div>
            </DialogContent>
          </Dialog>
        </div>
      )}

      {/* Invoices list */}
      {invoices.length === 0 ? (
        <div className="bg-white border border-zinc-200 rounded-xl p-12 text-center">
          <Receipt className="w-10 h-10 text-zinc-300 mx-auto mb-3" />
          <p className="text-sm text-zinc-500">No invoices yet</p>
        </div>
      ) : (
        <div className="bg-white border border-zinc-200 rounded-xl divide-y divide-zinc-100">
          {invoices.map((invoice) => {
            const statusConf = STATUS_CONFIG[invoice.status] || STATUS_CONFIG.sent;
            return (
              <div key={invoice.id} className="p-5 flex flex-wrap items-center gap-4">
                <div className="w-10 h-10 rounded-lg bg-zinc-100 flex items-center justify-center flex-shrink-0">
                  <DollarSign className="w-5 h-5 text-zinc-500" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-sm font-semibold text-zinc-900">
                      ${invoice.amount?.toFixed(2)}
                    </span>
                    <span className="text-xs text-zinc-400">{invoice.invoice_number}</span>
                  </div>
                  <p className="text-sm text-zinc-500 truncate mt-0.5">{invoice.description}</p>
                </div>
                <div className="flex items-center gap-1.5 text-xs text-zinc-400">
                  <Calendar className="w-3 h-3" />
                  Due {format(new Date(invoice.due_date), "MMM d, yyyy")}
                </div>

                {!isClient ? (
                  <Select
                    value={invoice.status || "sent"}
                    onValueChange={(val) => handleStatusChange(invoice.id, val)}
                  >
                    <SelectTrigger className="w-28 h-8">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="sent">Sent</SelectItem>
                      <SelectItem value="paid">Paid</SelectItem>
                      <SelectItem value="overdue">Overdue</SelectItem>
                    </SelectContent>
                  </Select>
                ) : (
                  <Badge variant="outline" className={`${statusConf.className} text-xs`}>
                    {statusConf.label}
                  </Badge>
                )}

                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => handlePrint(invoice)}
                >
                  <Download className="w-3.5 h-3.5 mr-1.5" />
                  PDF
                </Button>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}